palavras_forca = [
    "abacaxi", "amarelo", "banana", "carro", "dado", "elefante", "futebol", 
    "guitarra", "hambúrguer", "internet", "jardim", "ketchup", "limão", 
    "morango", "navio", "óculos", "pinguim", "queijo", "raio", "sapato", 
    "tigre", "uva", "violão", "xadrez", "zebra", "avião", "bola", "cachorro", 
    "dança", "escola", "foguete", "gato", "hospital", "inverno", "janela", 
    "kiwi", "laranja", "maçã", "nuvem", "ovo", "pato", "quadrado", "rato", 
    "sol", "tubarão", "urso", "vela", "waffle", "xícara", "yoga", "zangão"
]


dicas = [
    "Fruta tropical de casca dura e polpa suculenta.",
    "Cor primária associada à luz solar e ao otimismo.",
    "Fruta de casca amarela consumida em todo o mundo.",
    "Veículo terrestre motorizado utilizado para transporte.",
    "Objeto cúbico usado em jogos de azar.",
    "Mamífero terrestre de grande porte com tromba.",
    "Esporte praticado com uma bola e pés.",
    "Instrumento musical de cordas e corpo oco.",
    "Sanduíche de carne grelhada entre pães.",
    "Rede global de computadores interconectados.",
    "Espaço cultivado com plantas ornamentais.",
    "Molho condimentado à base de tomate e especiarias.",
    "Fruta cítrica verde com sabor ácido.",
    "Fruta vermelha e suculenta.",
    "Embarcação utilizada para navegação marítima.",
    "Dispositivo para correção da visão.",
    "Ave marinha de plumagem branca e preta.",
    "Alimento lácteo derivado do leite coalhado.",
    "Fenômeno natural de descarga elétrica na atmosfera.",
    "Calçado que cobre o pé e parte da perna.",
    "Animal felino de grande porte e listrado.",
    "Fruta arredondada de casca roxa-escura.",
    "Instrumento musical de cordas e caixa de ressonância.",
    "Jogo de tabuleiro estratégico para dois jogadores.",
    "Animal listrado preto e branco da savana africana.",
    "Aeronave mais pesada que o ar que voa pelos céus.",
    "Esfera usada em diversos esportes.",
    "Animal doméstico de estimação.",
    "Atividade de movimento rítmico e coordenado.",
    "Local de ensino e aprendizagem para estudantes.",
    "Veículo espacial de propulsão a jato.",
    "Animal de estimação felino e doméstico.",
    "Estabelecimento de cuidados médicos.",
    "Estação do ano caracterizada por temperaturas baixas.",
    "Abertura em uma parede para entrada de luz e ar.",
    "Fruta pequena e peluda de sabor doce e azedo.",
    "Fruta cítrica de cor alaranjada.",
    "Fruta redonda e comestível.",
    "Massa de partículas de água no céu.",
    "Produto de galinha usado como alimento.",
    "Ave aquática de penas coloridas e patas achatadas.",
    "Figura geométrica com quatro lados iguais.",
    "Roedor de cauda longa e pelos curtos.",
    "Estrela que ilumina o dia.",
    "Grande animal marinho com dentes afiados.",
    "Mamífero carnívoro de pelo espesso.",
    "Objeto inflamável para iluminar ambientes.",
    "Alimento em formato de massa fofa e doce.",
    "Recipiente para bebidas quentes.",
    "Prática de meditação e exercícios corporais.",
    "Inseto voador usado em atividades agrícolas."
]
